### ISSUE TITLE
Source code of shared libraries

### ISSUE THREAD

**Issue by GrauBlitz** [HummerX/BMSAIT#6]
Moin,

Are there any plans to release the source code of the shared libraries to contribute/extend the project or are they closed source?

Grüße

**Comment by HummerX** [comment]
Actually I hoped that lightingtools would publish the updated library sometime.
My changes are no secret and I'll be glad to share them.

**Comment by HummerX** [comment]
I uploaded my changes to lightnigvipers F4SharedMem.dll here:    https://github.com/HummerX/lightningstools
